### ISSUE TITLE
readme should mention that a JDK needs to be installed

### ISSUE THREAD

**Issue by matthargett** [pivotal-cf/react-starter#6]
when running the 'gulp' command as mentioned in the README, I got a UI prompt to install a JDK. 
I ended up doing 'brew install Caskroom/cask/xamarin-jdk', but there may be a better package.
Let me know the preferred way to install a JDK and I'll submit a pull request to update the README.

**Comment by charleshansen** [comment]
I'm not aware of a preferred way to install a JDK, especially not across operating systems. Java is usually already installed on my work computers and I usually manually download an installer at home. That said, I don't think xamarin is the one you want, since it is an Android jdk. I'd be happy with a parenthetical mentioning you will need to install Java similar to the one about installing C and Python, but I'd rather not specify exactly how to install it. As a side note, I think you only need Java for Selenium.

**Comment by matthargett** [comment]
How does sprout-wrap/soloist/librarian-chef/etc do it for the initial workstation bring-up these days? I browsed around those repos for a JDK recipe, but couldn't find one and don't remember how it used to work. There is a chef recipe, of course -- I can reference that but would prefer to do whatever would allow for consistent installation of other dependencies (like postgresql, redis, etc).

**Comment by rdy** [comment]
i've switched the default to use phantomjs by default, if the user wishes to use alternative browsers it will require the JDK because selenium requires it. But at least there won't be a strict requirement with the JDK.
